apiVersion: apps/v1
kind: Deployment
metadata:
  name: string-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stringgenerator
  template:
    metadata:
      labels:
        app: stringgenerator
    spec:
      containers:
        - name: stringgenerator
          image: lauraleonilla/string-generator:latest