apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-app
  template:
    metadata:
      labels:
        app: project-app
    spec:
      volumes:
        - name: shared-project
          persistentVolumeClaim:
            claimName: project-claim
      containers:
        - name: project-app
          image: lauraleonilla/projectappwlist:latest
          volumeMounts:
          - name: shared-project
            mountPath: /usr/src/app/files