apiVersion: v1
kind: Service
metadata:
  name: project-srv
spec:
  type: ClusterIP
  selector:
    app: project-app
  ports:
    - name: project
      port: 2345
      protocol: TCP
      targetPort: 3000