apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-web-server
  template:
    metadata:
      labels:
        app: html-web-server
    spec:
      containers:
        - name: html-web-server
          image: lauraleonilla/html-web-server:latest